version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    env_file: ./.env
    ports:
      - $NODE_PORT:$NODE_PORT
    environment:
      - DB_HOST=postgres
      - DB_USER=$POSTGRESS_USER
      - DB_PASSWORD=$POSTGRESS_PASSWORD
      - DB_NAME=$POSTGRESS_DB
      - DB_PORT=$POSTGRESS_PORT
      - NODE_PORT=$NODE_PORT
    depends_on:
      - postgres
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - $WEB_PORT:$WEB_DEV_PORT
    links:
      - "server:se"

  postgres:
    image: postgres:9.6.2-alpine
    env_file: ./.env
    environment:
      POSTGRES_USER: $POSTGRESS_USER
      POSTGRES_PASSWORD: $POSTGRESS_PASSWORD
      POSTGRES_DB: $POSTGRESS_DB
    ports:
      - $POSTGRESS_PORT:$POSTGRESS_PORT
